DROP TABLE RENTAL;
DROP TABLE MEMBER;
DROP TABLE BOOK;

CREATE TABLE BOOK(
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    AUTHOR VARCHAR2(20),
    PUBLISHER VARCHAR2(50)
);

CREATE TABLE MEMBER(
    MEMBER_ID NUMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20)
);

CREATE TABLE RENTAL(
    RENTAL_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    RENTAL_DATE DATE DEFAULT SYSDATE,
    RETURN_DATE DATE,
    CONSTRAINT FK_RENTAL_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_RENTAL_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

CREATE SEQUENCE SEQ_BOOK_ID; 
CREATE SEQUENCE SEQ_MEMBER_ID; 
CREATE SEQUENCE SEQ_RENTAL_ID; 

INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '자바의 정석', '남궁성', '한빛');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '해리포터와 마법사의 돌', '최지원', '문학인');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '어린왕자', '토마스', '사람');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '1984', '조지 오웰', '열린');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '데이터베이스개론', '허밍웨이', '한빛');

INSERT INTO MEMBER VALUES(SEQ_MEMBER_ID.NEXTVAL, '김민수', '010-4498-3434');
INSERT INTO MEMBER VALUES(SEQ_MEMBER_ID.NEXTVAL, '최무식', '010-2345-5645');
INSERT INTO MEMBER VALUES(SEQ_MEMBER_ID.NEXTVAL, '박준태', '010-4562-8975');

INSERT INTO RENTAL
VALUES(SEQ_RENTAL_ID.NEXTVAL, 2, 3, SYSDATE - 10, SYSDATE);

INSERT INTO RENTAL
VALUES(SEQ_RENTAL_ID.NEXTVAL, 1, 1, SYSDATE, NULL);

COMMIT;