--DROP TABLE TEST;

CREATE TABLE TEST(
    TNO NUMBER PRIMARY KEY,
    TNAME VARCHAR2(100) NOT NULL,
    TDATE DATE DEFAULT SYSDATE NOT NULL
);

SELECT * FROM TEST;

INSERT INTO TEST VALUES(1, '홍길동', DEFAULT);
INSERT INTO TEST VALUES(2, '김개똥', DEFAULT);

commit;

CREATE TABLE MEMBER(
    USER_NO NUMBER PRIMARY KEY, --회원번호
    USER_ID VARCHAR2(30) NOT NULL UNIQUE, --아이디
    USER_PWD VARCHAR2(30) NOT NULL, --비밀번호
    USER_NAME VARCHAR2(20) NOT NULL, --이름
    GENDER CHAR(1) CHECK(GENDER IN ('M', 'F')), --성별
    AGE NUMBER, --나이
    EMAIL VARCHAR(30), --이메일
    PHONE CHAR(11), --핸드폰주소(하이픈제외)
    ADDRESS VARCHAR2(100), --주소
    HOBBY VARCHAR2(50), --취미
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL --가입일
);

ALTER SEQUENCE SEQ_USERNO
NOCACHE;

COMMIT;

select * from MEMBER;





